services:
  iot_server:
    build:
      context: .
    container_name: iot_server
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - iot_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - iot_network

volumes:
  mongodb_data:

networks:
  iot_network:
