// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA77tRIjmzjpx0drmqwmXNQ4QMHoNTrY7E',
    appId: '1:626719385140:web:acaa1ed76aa6cf94ed8c61',
    messagingSenderId: '626719385140',
    projectId: 'smartparking-mobileflutterapp',
    authDomain: 'smartparking-mobileflutterapp.firebaseapp.com',
    storageBucket: 'smartparking-mobileflutterapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs7LQg3QhGyhse7BNY9viiBhJtaejX1Ls',
    appId: '1:626719385140:android:1035c9ba68ff7aaded8c61',
    messagingSenderId: '626719385140',
    projectId: 'smartparking-mobileflutterapp',
    storageBucket: 'smartparking-mobileflutterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoI5ac_dLHdcMSWyU0GgmSFksffppGc6I',
    appId: '1:626719385140:ios:43763bb2599758b0ed8c61',
    messagingSenderId: '626719385140',
    projectId: 'smartparking-mobileflutterapp',
    storageBucket: 'smartparking-mobileflutterapp.firebasestorage.app',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoI5ac_dLHdcMSWyU0GgmSFksffppGc6I',
    appId: '1:626719385140:ios:43763bb2599758b0ed8c61',
    messagingSenderId: '626719385140',
    projectId: 'smartparking-mobileflutterapp',
    storageBucket: 'smartparking-mobileflutterapp.firebasestorage.app',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA77tRIjmzjpx0drmqwmXNQ4QMHoNTrY7E',
    appId: '1:626719385140:web:18622cab27834fe9ed8c61',
    messagingSenderId: '626719385140',
    projectId: 'smartparking-mobileflutterapp',
    authDomain: 'smartparking-mobileflutterapp.firebaseapp.com',
    storageBucket: 'smartparking-mobileflutterapp.firebasestorage.app',
  );
}
